# Generated by Django 4.2.20 on 2025-03-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lavagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_lavagem', models.CharField(choices=[('simples', 'Simples'), ('completa', 'Completa'), ('especial', 'Especial')], max_length=20)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('funcionarios', models.ManyToManyField(blank=True, to='app.funcionario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.veiculo')),
            ],
        ),
        migrations.DeleteModel(
            name='Agendamento',
        ),
    ]
